"""
The simulated "AI-readable merchant API".

This is the ONLY layer that talks to the product database. The agent
(and, indirectly, the LLM via tool calls) reaches products exclusively
through these functions - never through raw SQL, and the LLM is never
handed DB access directly. Everything returned here is real, retrieved
data; nothing here is generated by the LLM.
"""
from __future__ import annotations

from typing import Any, Optional

from .database import get_session
from .models import Product

# All categories that exist in the seeded catalog - included in the tool
# schema description so the model has a sense of what's actually sellable
# instead of guessing category names.
KNOWN_CATEGORIES = [
    "running shoes",
    "casual sneakers",
    "formal shoes",
    "backpacks",
    "wireless earbuds",
    "smartwatches",
]


def search_products(
    category: Optional[str] = None,
    keywords: Optional[list[str]] = None,
    min_price: Optional[float] = None,
    max_price: Optional[float] = None,
    limit: int = 8,
) -> list[dict[str, Any]]:
    """Structured filter search over the merchant catalog (federated across
    all simulated merchants). Hard constraints (price, category) are
    applied in SQL; keywords do a simple case-insensitive match against
    name/description/brand/attributes so fuzzy phrases like 'marathon
    training' still surface relevant products even if the category is off.
    """
    session = get_session()
    try:
        query = session.query(Product)

        if category:
            query = query.filter(Product.category.ilike(f"%{category}%"))
        if min_price is not None:
            query = query.filter(Product.price >= min_price)
        if max_price is not None:
            query = query.filter(Product.price <= max_price)

        candidates = query.all()

        if keywords:
            lowered = [k.lower() for k in keywords if k]

            def matches(p: Product) -> bool:
                haystack = " ".join(
                    [
                        p.name,
                        p.brand,
                        p.category,
                        p.description,
                        " ".join(f"{k} {v}" for k, v in (p.attributes or {}).items()),
                    ]
                ).lower()
                return any(kw in haystack for kw in lowered)

            keyword_matches = [p for p in candidates if matches(p)]
            # Keyword matching narrows results when it finds any; if none
            # match (e.g. overly specific phrasing), fall back to the
            # category/price-filtered set rather than returning nothing.
            if keyword_matches:
                candidates = keyword_matches

        candidates.sort(key=lambda p: (-p.rating, p.price))
        return [p.to_dict() for p in candidates[:limit]]
    finally:
        session.close()


def get_product(product_id: int) -> Optional[dict[str, Any]]:
    session = get_session()
    try:
        product = session.get(Product, product_id)
        return product.to_dict() if product else None
    finally:
        session.close()


def get_product_by_sku(sku: str) -> Optional[dict[str, Any]]:
    """Used by the order/checkout flow, which naturally deals in skus
    (what the recommendation agent and the user-facing UI reference)
    rather than internal numeric ids."""
    session = get_session()
    try:
        product = session.query(Product).filter(Product.sku == sku).first()
        return product.to_dict() if product else None
    finally:
        session.close()


def check_inventory(product_id: int) -> dict[str, Any]:
    product = get_product(product_id)
    if not product:
        return {"product_id": product_id, "found": False, "in_stock": False, "stock_qty": 0}
    return {
        "product_id": product_id,
        "found": True,
        "in_stock": product["in_stock"],
        "stock_qty": product["stock_qty"],
    }


# Ollama/OpenAI-style tool schema for search_products. get_product and
# check_inventory are called directly by the backend when needed (e.g. at
# order time later) rather than exposed as tools here, to keep the
# recommendation-phase tool surface small and predictable for an 8B model.
SEARCH_PRODUCTS_TOOL = {
    "type": "function",
    "function": {
        "name": "search_products",
        "description": (
            "Search the merchant product catalog. Known categories: "
            + ", ".join(KNOWN_CATEGORIES)
            + ". Returns real product listings with price, rating, stock, and attributes - "
            "never invent products outside of what this tool returns."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Product category to filter by, e.g. 'running shoes'",
                },
                "keywords": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Free-form keywords/phrases from the user's request",
                },
                "min_price": {"type": "number", "description": "Minimum price in INR"},
                "max_price": {"type": "number", "description": "Maximum price in INR"},
            },
            "required": [],
        },
    },
}
