"""
Simulated merchant catalog seed data.

Three fictional merchants, each an "AI-readable" storefront for a
different category cluster, so search_products() is genuinely federating
across merchants rather than reading one flat list. Brands are invented
(this is simulated data for a demo, not real inventory).
"""

MERCHANTS = [
    {"name": "SprintHub", "description": "Footwear specialist - running, casual, and formal shoes."},
    {"name": "UrbanGear Co.", "description": "Bags and outdoor carry gear."},
    {"name": "PulseTech", "description": "Wearables and audio electronics."},
]

# price in INR. attributes are category-specific free-form facts.
PRODUCTS = [
    # ---- SprintHub: Running Shoes ----
    {"merchant": "SprintHub", "sku": "RUN-001", "name": "AeroStride Marathon Pro", "brand": "AeroStride",
     "category": "running shoes", "price": 4499, "rating": 4.6, "review_count": 812, "stock_qty": 24,
     "description": "High-cushion daily trainer built for long-distance marathon training.",
     "attributes": {"use_case": "marathon training", "cushioning": "high", "drop_mm": "8",
                    "weight_g": "260", "sizes_available": "6,7,8,9,10,11", "color": "black/orange"}},
    {"merchant": "SprintHub", "sku": "RUN-002", "name": "AeroStride Tempo Racer", "brand": "AeroStride",
     "category": "running shoes", "price": 5299, "rating": 4.4, "review_count": 340, "stock_qty": 12,
     "description": "Lightweight racing flat for tempo runs and race day.",
     "attributes": {"use_case": "racing", "cushioning": "medium", "drop_mm": "6",
                    "weight_g": "195", "sizes_available": "7,8,9,10", "color": "white/red"}},
    {"merchant": "SprintHub", "sku": "RUN-003", "name": "Velocore Endurance 2", "brand": "Velocore",
     "category": "running shoes", "price": 3799, "rating": 4.3, "review_count": 601, "stock_qty": 30,
     "description": "Budget-friendly cushioned trainer, popular for first-time marathoners.",
     "attributes": {"use_case": "marathon training", "cushioning": "high", "drop_mm": "10",
                    "weight_g": "280", "sizes_available": "6,7,8,9,10,11,12", "color": "grey/blue"}},
    {"merchant": "SprintHub", "sku": "RUN-004", "name": "Velocore Trailblaze GTX", "brand": "Velocore",
     "category": "running shoes", "price": 6199, "rating": 4.5, "review_count": 275, "stock_qty": 8,
     "description": "Waterproof trail running shoe with aggressive grip.",
     "attributes": {"use_case": "trail running", "cushioning": "medium", "drop_mm": "6",
                    "weight_g": "310", "sizes_available": "7,8,9,10,11", "color": "olive/black"}},
    {"merchant": "SprintHub", "sku": "RUN-005", "name": "Nimbus Fly Knit", "brand": "Nimbus",
     "category": "running shoes", "price": 3999, "rating": 4.2, "review_count": 498, "stock_qty": 40,
     "description": "Breathable knit upper trainer for everyday runs and marathon base miles.",
     "attributes": {"use_case": "marathon training", "cushioning": "medium", "drop_mm": "8",
                    "weight_g": "245", "sizes_available": "6,7,8,9,10", "color": "navy/lime"}},
    {"merchant": "SprintHub", "sku": "RUN-006", "name": "Nimbus StrideMax", "brand": "Nimbus",
     "category": "running shoes", "price": 4899, "rating": 4.7, "review_count": 920, "stock_qty": 18,
     "description": "Max-cushion recovery-friendly shoe, popular with marathon runners for long runs.",
     "attributes": {"use_case": "marathon training", "cushioning": "very high", "drop_mm": "10",
                    "weight_g": "290", "sizes_available": "7,8,9,10,11", "color": "black/white"}},
    {"merchant": "SprintHub", "sku": "RUN-007", "name": "FlashFeet Sprint X", "brand": "FlashFeet",
     "category": "running shoes", "price": 2999, "rating": 3.9, "review_count": 210, "stock_qty": 55,
     "description": "Entry-level running shoe, good value for casual joggers.",
     "attributes": {"use_case": "casual jogging", "cushioning": "medium", "drop_mm": "10",
                    "weight_g": "270", "sizes_available": "6,7,8,9,10,11", "color": "red/black"}},
    {"merchant": "SprintHub", "sku": "RUN-008", "name": "AeroStride Cloud9", "brand": "AeroStride",
     "category": "running shoes", "price": 7499, "rating": 4.8, "review_count": 156, "stock_qty": 6,
     "description": "Premium carbon-plated marathon racer for sub-4-hour goals.",
     "attributes": {"use_case": "marathon racing", "cushioning": "high", "drop_mm": "8",
                    "weight_g": "220", "sizes_available": "7,8,9,10", "color": "electric blue"}},
    {"merchant": "SprintHub", "sku": "RUN-009", "name": "Velocore Pace Setter", "brand": "Velocore",
     "category": "running shoes", "price": 4199, "rating": 4.1, "review_count": 388, "stock_qty": 21,
     "description": "Stability trainer for overpronators doing marathon training.",
     "attributes": {"use_case": "marathon training", "stability": "yes", "cushioning": "medium",
                    "drop_mm": "8", "sizes_available": "7,8,9,10,11", "color": "grey/orange"}},
    {"merchant": "SprintHub", "sku": "RUN-010", "name": "Nimbus Featherlite", "brand": "Nimbus",
     "category": "running shoes", "price": 3499, "rating": 4.0, "review_count": 264, "stock_qty": 33,
     "description": "Ultra-light trainer for speed workouts.",
     "attributes": {"use_case": "speed training", "cushioning": "low", "drop_mm": "4",
                    "weight_g": "180", "sizes_available": "6,7,8,9,10", "color": "yellow/black"}},

    # ---- SprintHub: Casual Sneakers ----
    {"merchant": "SprintHub", "sku": "CAS-001", "name": "UrbanWalk Classic", "brand": "UrbanWalk",
     "category": "casual sneakers", "price": 2499, "rating": 4.2, "review_count": 540,
     "stock_qty": 60, "description": "Everyday canvas sneaker for walking and casual wear.",
     "attributes": {"use_case": "everyday wear", "material": "canvas", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "CAS-002", "name": "UrbanWalk Retro 90", "brand": "UrbanWalk",
     "category": "casual sneakers", "price": 3299, "rating": 4.4, "review_count": 410,
     "stock_qty": 27, "description": "Retro-styled leather sneaker.",
     "attributes": {"use_case": "everyday wear", "material": "leather", "sizes_available": "7,8,9,10"}},
    {"merchant": "SprintHub", "sku": "CAS-003", "name": "FlashFeet StreetLite", "brand": "FlashFeet",
     "category": "casual sneakers", "price": 1899, "rating": 3.8, "review_count": 180,
     "stock_qty": 70, "description": "Budget everyday sneaker.",
     "attributes": {"use_case": "everyday wear", "material": "synthetic", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "CAS-004", "name": "Nimbus CloudWalk", "brand": "Nimbus",
     "category": "casual sneakers", "price": 3999, "rating": 4.5, "review_count": 322,
     "stock_qty": 19, "description": "Cushioned slip-on sneaker for all-day comfort.",
     "attributes": {"use_case": "all-day comfort", "material": "knit", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "CAS-005", "name": "Velocore UrbanX", "brand": "Velocore",
     "category": "casual sneakers", "price": 2999, "rating": 4.0, "review_count": 205,
     "stock_qty": 44, "description": "Versatile sneaker for city commuting.",
     "attributes": {"use_case": "commuting", "material": "synthetic leather", "sizes_available": "7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "CAS-006", "name": "AeroStride Lifestyle", "brand": "AeroStride",
     "category": "casual sneakers", "price": 4499, "rating": 4.3, "review_count": 150,
     "stock_qty": 15, "description": "Sport-lifestyle crossover sneaker.",
     "attributes": {"use_case": "lifestyle", "material": "mesh/leather", "sizes_available": "7,8,9,10"}},
    {"merchant": "SprintHub", "sku": "CAS-007", "name": "UrbanWalk Slip-On", "brand": "UrbanWalk",
     "category": "casual sneakers", "price": 1699, "rating": 3.9, "review_count": 260,
     "stock_qty": 80, "description": "No-lace slip-on for quick errands.",
     "attributes": {"use_case": "errands", "material": "canvas", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "CAS-008", "name": "FlashFeet Bold", "brand": "FlashFeet",
     "category": "casual sneakers", "price": 2199, "rating": 3.7, "review_count": 130,
     "stock_qty": 50, "description": "Bold-colored sneaker for teens and young adults.",
     "attributes": {"use_case": "everyday wear", "material": "synthetic", "sizes_available": "5,6,7,8,9"}},

    # ---- SprintHub: Formal Shoes ----
    {"merchant": "SprintHub", "sku": "FRM-001", "name": "Oakford Classic Oxford", "brand": "Oakford",
     "category": "formal shoes", "price": 3999, "rating": 4.4, "review_count": 190,
     "stock_qty": 22, "description": "Genuine leather oxford for office and formal events.",
     "attributes": {"use_case": "office", "material": "leather", "sizes_available": "7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "FRM-002", "name": "Oakford Derby Elite", "brand": "Oakford",
     "category": "formal shoes", "price": 4599, "rating": 4.5, "review_count": 145,
     "stock_qty": 14, "description": "Premium derby shoe with cushioned insole.",
     "attributes": {"use_case": "formal events", "material": "leather", "sizes_available": "7,8,9,10"}},
    {"merchant": "SprintHub", "sku": "FRM-003", "name": "Velocore OfficeStep", "brand": "Velocore",
     "category": "formal shoes", "price": 2799, "rating": 4.0, "review_count": 210,
     "stock_qty": 35, "description": "Comfort-focused formal shoe for long office days.",
     "attributes": {"use_case": "office", "material": "synthetic leather", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "FRM-004", "name": "Oakford Monk Strap", "brand": "Oakford",
     "category": "formal shoes", "price": 5299, "rating": 4.6, "review_count": 88,
     "stock_qty": 9, "description": "Double monk strap shoe for weddings and formal events.",
     "attributes": {"use_case": "formal events", "material": "leather", "sizes_available": "7,8,9,10"}},
    {"merchant": "SprintHub", "sku": "FRM-005", "name": "UrbanWalk Business Slip",
     "brand": "UrbanWalk", "category": "formal shoes", "price": 2299, "rating": 3.8,
     "review_count": 165, "stock_qty": 40, "description": "Slip-on formal shoe for business casual.",
     "attributes": {"use_case": "business casual", "material": "synthetic leather", "sizes_available": "6,7,8,9,10,11"}},
    {"merchant": "SprintHub", "sku": "FRM-006", "name": "Oakford Chelsea Boot", "brand": "Oakford",
     "category": "formal shoes", "price": 4899, "rating": 4.3, "review_count": 112,
     "stock_qty": 11, "description": "Leather chelsea boot, smart-casual to formal.",
     "attributes": {"use_case": "smart casual", "material": "leather", "sizes_available": "7,8,9,10,11"}},

    # ---- UrbanGear Co.: Backpacks ----
    {"merchant": "UrbanGear Co.", "sku": "BAG-001", "name": "TrailPack 30L", "brand": "TrailPack",
     "category": "backpacks", "price": 2999, "rating": 4.5, "review_count": 430,
     "stock_qty": 26, "description": "30L hiking backpack with rain cover.",
     "attributes": {"use_case": "hiking", "capacity_liters": "30", "water_resistant": "yes", "laptop_sleeve": "no"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-002", "name": "TrailPack CityCommuter", "brand": "TrailPack",
     "category": "backpacks", "price": 1999, "rating": 4.3, "review_count": 610,
     "stock_qty": 55, "description": "Slim commuter backpack with 15-inch laptop sleeve.",
     "attributes": {"use_case": "commuting", "capacity_liters": "20", "water_resistant": "yes", "laptop_sleeve": "15 inch"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-003", "name": "PeakGear Alpine 45L", "brand": "PeakGear",
     "category": "backpacks", "price": 5499, "rating": 4.7, "review_count": 190,
     "stock_qty": 8, "description": "45L trekking backpack for multi-day treks.",
     "attributes": {"use_case": "trekking", "capacity_liters": "45", "water_resistant": "yes", "laptop_sleeve": "no"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-004", "name": "UrbanCarry Everyday", "brand": "UrbanCarry",
     "category": "backpacks", "price": 1499, "rating": 4.0, "review_count": 350,
     "stock_qty": 90, "description": "Simple everyday backpack for school or college.",
     "attributes": {"use_case": "college", "capacity_liters": "18", "water_resistant": "no", "laptop_sleeve": "14 inch"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-005", "name": "PeakGear Summit 60L", "brand": "PeakGear",
     "category": "backpacks", "price": 7999, "rating": 4.8, "review_count": 76,
     "stock_qty": 4, "description": "60L expedition backpack with internal frame.",
     "attributes": {"use_case": "expedition", "capacity_liters": "60", "water_resistant": "yes", "laptop_sleeve": "no"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-006", "name": "UrbanCarry Anti-Theft Pro",
     "brand": "UrbanCarry", "category": "backpacks", "price": 3499, "rating": 4.4,
     "review_count": 288, "stock_qty": 33, "description": "Anti-theft commuter backpack with USB charging port.",
     "attributes": {"use_case": "commuting", "capacity_liters": "22", "water_resistant": "yes", "laptop_sleeve": "16 inch"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-007", "name": "TrailPack Daypack Mini", "brand": "TrailPack",
     "category": "backpacks", "price": 1299, "rating": 3.9, "review_count": 145,
     "stock_qty": 70, "description": "Lightweight daypack for short hikes or gym.",
     "attributes": {"use_case": "gym", "capacity_liters": "15", "water_resistant": "no", "laptop_sleeve": "no"}},
    {"merchant": "UrbanGear Co.", "sku": "BAG-008", "name": "PeakGear TrailRunner Vest",
     "brand": "PeakGear", "category": "backpacks", "price": 2799, "rating": 4.6,
     "review_count": 98, "stock_qty": 17, "description": "Hydration vest pack for trail running.",
     "attributes": {"use_case": "trail running", "capacity_liters": "8", "water_resistant": "yes", "laptop_sleeve": "no"}},

    # ---- PulseTech: Wireless Earbuds ----
    {"merchant": "PulseTech", "sku": "EAR-001", "name": "PulseBuds Air 2", "brand": "PulseTech",
     "category": "wireless earbuds", "price": 2499, "rating": 4.3, "review_count": 920,
     "stock_qty": 65, "description": "Compact true wireless earbuds with 24h battery case.",
     "attributes": {"battery_life_hours": "24", "anc": "no", "water_resistant": "IPX4", "color": "black"}},
    {"merchant": "PulseTech", "sku": "EAR-002", "name": "PulseBuds ANC Pro", "brand": "PulseTech",
     "category": "wireless earbuds", "price": 4999, "rating": 4.6, "review_count": 540,
     "stock_qty": 30, "description": "Active noise cancelling earbuds for commutes and travel.",
     "attributes": {"battery_life_hours": "30", "anc": "yes", "water_resistant": "IPX4", "color": "white"}},
    {"merchant": "PulseTech", "sku": "EAR-003", "name": "SonicWave Sport", "brand": "SonicWave",
     "category": "wireless earbuds", "price": 1999, "rating": 4.0, "review_count": 410,
     "stock_qty": 80, "description": "Sweat-resistant earbuds designed for workouts and running.",
     "attributes": {"battery_life_hours": "20", "anc": "no", "water_resistant": "IPX7", "color": "orange"}},
    {"merchant": "PulseTech", "sku": "EAR-004", "name": "SonicWave Studio", "brand": "SonicWave",
     "category": "wireless earbuds", "price": 6499, "rating": 4.7, "review_count": 210,
     "stock_qty": 12, "description": "Hi-res audio earbuds with premium drivers.",
     "attributes": {"battery_life_hours": "28", "anc": "yes", "water_resistant": "IPX4", "color": "black"}},
    {"merchant": "PulseTech", "sku": "EAR-005", "name": "PulseBuds Lite", "brand": "PulseTech",
     "category": "wireless earbuds", "price": 1299, "rating": 3.8, "review_count": 630,
     "stock_qty": 100, "description": "Budget everyday earbuds.",
     "attributes": {"battery_life_hours": "18", "anc": "no", "water_resistant": "IPX2", "color": "blue"}},
    {"merchant": "PulseTech", "sku": "EAR-006", "name": "SonicWave RunBeat", "brand": "SonicWave",
     "category": "wireless earbuds", "price": 2299, "rating": 4.2, "review_count": 355,
     "stock_qty": 48, "description": "Ear-hook earbuds that stay secure during marathon training runs.",
     "attributes": {"use_case": "running", "battery_life_hours": "22", "anc": "no",
                    "water_resistant": "IPX6", "color": "green"}},
    {"merchant": "PulseTech", "sku": "EAR-007", "name": "PulseBuds Executive", "brand": "PulseTech",
     "category": "wireless earbuds", "price": 3799, "rating": 4.4, "review_count": 240,
     "stock_qty": 25, "description": "Earbuds tuned for calls with 4-mic noise-cancelling.",
     "attributes": {"use_case": "calls", "battery_life_hours": "26", "anc": "yes",
                    "water_resistant": "IPX4", "color": "silver"}},
    {"merchant": "PulseTech", "sku": "EAR-008", "name": "SonicWave Kids", "brand": "SonicWave",
     "category": "wireless earbuds", "price": 999, "rating": 3.6, "review_count": 150,
     "stock_qty": 60, "description": "Volume-limited earbuds designed for children.",
     "attributes": {"use_case": "kids", "battery_life_hours": "15", "anc": "no",
                    "water_resistant": "IPX2", "color": "pink"}},

    # ---- PulseTech: Smartwatches ----
    {"merchant": "PulseTech", "sku": "WCH-001", "name": "PulseFit Run GPS", "brand": "PulseTech",
     "category": "smartwatches", "price": 5999, "rating": 4.5, "review_count": 480,
     "stock_qty": 22, "description": "Running-focused smartwatch with built-in GPS and marathon training plans.",
     "attributes": {"use_case": "marathon training", "battery_life_days": "7", "gps": "yes", "display": "AMOLED"}},
    {"merchant": "PulseTech", "sku": "WCH-002", "name": "PulseFit Lite", "brand": "PulseTech",
     "category": "smartwatches", "price": 2499, "rating": 4.0, "review_count": 690,
     "stock_qty": 70, "description": "Affordable fitness tracker watch.",
     "attributes": {"use_case": "everyday fitness", "battery_life_days": "10", "gps": "no", "display": "LCD"}},
    {"merchant": "PulseTech", "sku": "WCH-003", "name": "SonicWave Chrono Pro", "brand": "SonicWave",
     "category": "smartwatches", "price": 8999, "rating": 4.7, "review_count": 205,
     "stock_qty": 9, "description": "Premium multisport watch with advanced running metrics.",
     "attributes": {"use_case": "marathon training", "battery_life_days": "14", "gps": "yes", "display": "AMOLED"}},
    {"merchant": "PulseTech", "sku": "WCH-004", "name": "PulseFit Classic", "brand": "PulseTech",
     "category": "smartwatches", "price": 3999, "rating": 4.1, "review_count": 320,
     "stock_qty": 40, "description": "All-round smartwatch with heart rate and sleep tracking.",
     "attributes": {"use_case": "everyday", "battery_life_days": "8", "gps": "no", "display": "AMOLED"}},
    {"merchant": "PulseTech", "sku": "WCH-005", "name": "SonicWave Active", "brand": "SonicWave",
     "category": "smartwatches", "price": 4499, "rating": 4.3, "review_count": 260,
     "stock_qty": 18, "description": "Rugged sports watch built for trail runners.",
     "attributes": {"use_case": "trail running", "battery_life_days": "9", "gps": "yes", "display": "LCD"}},
    {"merchant": "PulseTech", "sku": "WCH-006", "name": "PulseFit Kids", "brand": "PulseTech",
     "category": "smartwatches", "price": 1799, "rating": 3.7, "review_count": 140,
     "stock_qty": 55, "description": "Simple activity watch designed for children.",
     "attributes": {"use_case": "kids", "battery_life_days": "5", "gps": "no", "display": "LCD"}},
    {"merchant": "PulseTech", "sku": "WCH-007", "name": "SonicWave Business", "brand": "SonicWave",
     "category": "smartwatches", "price": 6499, "rating": 4.4, "review_count": 175,
     "stock_qty": 14, "description": "Elegant smartwatch with notifications and long battery life.",
     "attributes": {"use_case": "everyday", "battery_life_days": "12", "gps": "no", "display": "AMOLED"}},
    {"merchant": "PulseTech", "sku": "WCH-008", "name": "PulseFit Marathon Edition",
     "brand": "PulseTech", "category": "smartwatches", "price": 7499, "rating": 4.8,
     "review_count": 96, "stock_qty": 6, "description": "Limited edition marathon watch with race-day pacing tools.",
     "attributes": {"use_case": "marathon racing", "battery_life_days": "10", "gps": "yes", "display": "AMOLED"}},
]
